-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 20:18:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hottahue
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hottahue
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hottahue` DEFAULT CHARACTER SET utf8 ;
USE `hottahue` ;

-- -----------------------------------------------------
-- Table `hottahue`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`User` (
  `Id` INT UNSIGNED NOT NULL DEFAULT id,
  `UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hottahue`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `hottahue`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`Owner` (
  `id` INT GENERATED ALWAYS AS (id) VIRTUAL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = CSV;


-- -----------------------------------------------------
-- Table `hottahue`.`Horse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`Horse` (
  `id` INT GENERATED ALWAYS AS (id) VIRTUAL,
  `Owner_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Owner_id`),
  INDEX `fk_Horse_Owner1_idx` (`Owner_id` ASC),
  CONSTRAINT `fk_Horse_Owner1`
    FOREIGN KEY (`Owner_id`)
    REFERENCES `hottahue`.`Owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hottahue`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`Owner` (
  `id` INT GENERATED ALWAYS AS (id) VIRTUAL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = CSV;


-- -----------------------------------------------------
-- Table `hottahue`.`HoofingDate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`HoofingDate` (
  `smith_id` INT NOT NULL,
  `horse_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `leg` TINYINT(4) NOT NULL,
  PRIMARY KEY (`smith_id`, `horse_id`),
  INDEX `fk_Smith_has_Horse_Horse1_idx` (`horse_id` ASC),
  INDEX `fk_Smith_has_Horse_Smith1_idx` (`smith_id` ASC),
  CONSTRAINT `fk_Smith_has_Horse_Smith1`
    FOREIGN KEY (`smith_id`)
    REFERENCES `hottahue`.`Smith` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Smith_has_Horse_Horse1`
    FOREIGN KEY (`horse_id`)
    REFERENCES `hottahue`.`Horse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hottahue`.`Smith`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`Smith` (
  `id` INT GENERATED ALWAYS AS (id) VIRTUAL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hottahue`.`HoofingDate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hottahue`.`HoofingDate` (
  `smith_id` INT NOT NULL,
  `horse_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `leg` TINYINT(4) NOT NULL,
  PRIMARY KEY (`smith_id`, `horse_id`),
  INDEX `fk_Smith_has_Horse_Horse1_idx` (`horse_id` ASC),
  INDEX `fk_Smith_has_Horse_Smith1_idx` (`smith_id` ASC),
  CONSTRAINT `fk_Smith_has_Horse_Smith1`
    FOREIGN KEY (`smith_id`)
    REFERENCES `hottahue`.`Smith` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Smith_has_Horse_Horse1`
    FOREIGN KEY (`horse_id`)
    REFERENCES `hottahue`.`Horse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
